In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_excel("Refined ODA latest.xlsx")

In [66]:
df.head()

,Time,Time Code,Algeria [DZA] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD],Algeria [DZA] - GDP (current US$) [NY.GDP.MKTP.CD],Algeria [DZA] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],Algeria [DZA] - Gross capital formation (current US$) [NE.GDI.TOTL.CD],Algeria [DZA] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD],Angola [AGO] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD],Angola [AGO] - GDP (current US$) [NY.GDP.MKTP.CD],Angola [AGO] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],...,Zambia [ZMB] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD],Zambia [ZMB] - GDP (current US$) [NY.GDP.MKTP.CD],Zambia [ZMB] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],Zambia [ZMB] - Gross capital formation (current US$) [NE.GDI.TOTL.CD],Zambia [ZMB] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD],Zimbabwe [ZWE] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD],Zimbabwe [ZWE] - GDP (current US$) [NY.GDP.MKTP.CD],Zimbabwe [ZWE] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],Zimbabwe [ZWE] - Gross capital formation (current US$) [NE.GDI.TOTL.CD],Zimbabwe [ZWE] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD]
0,1980,YR1980,205160003.662109,4.234583e+10,0.790607,1.654745e+10,1.824128e+10,52439998.626709,5.934074e+09,..,...,317209991.455078,3.882890e+09,3.035622,..,..,160639999.389648,6.678868e+09,14.420684,1.131198e+09,8.205660e+08
1,1981,YR1981,167070007.324219,4.434859e+10,2.999996,1.640481e+10,1.804992e+10,60220001.220703,5.553824e+09,-4.400001,...,230800003.051758,4.006207e+09,6.167957,..,..,174669998.168945,8.011374e+09,12.525425,1.667639e+09,9.560224e+08
2,1982,YR1982,134699996.948242,4.520717e+10,6.400004,1.685470e+10,1.772574e+10,59069999.694824,5.553824e+09,0,...,315489990.234375,3.870075e+09,-2.812783,..,..,213380004.882813,8.539701e+09,2.634297,1.627132e+09,9.952887e+08
3,1983,YR1983,93279998.779297,4.880137e+10,5.400003,1.833445e+10,1.937855e+10,73879997.253418,5.787824e+09,4.200001,...,214990005.493164,3.321048e+09,-1.966689,..,..,207449996.948242,7.764067e+09,1.585305,1.110662e+09,6.858990e+08
4,1984,YR1984,120980003.356934,5.369855e+10,5.599997,1.888279e+10,1.793965e+10,93410003.662109,6.135166e+09,6.000002,...,235729995.727539,2.719801e+09,-0.336835,..,..,296799987.792969,6.352126e+09,-1.907360,1.082117e+09,1.042834e+09

In [67]:
df.columns

Index(['Time', 'Time Code',
       'Algeria [DZA] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD]',
       'Algeria [DZA] - GDP (current US$) [NY.GDP.MKTP.CD]',
       'Algeria [DZA] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       'Algeria [DZA] - Gross capital formation (current US$) [NE.GDI.TOTL.CD]',
       'Algeria [DZA] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD]',
       'Angola [AGO] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD]',
       'Angola [AGO] - GDP (current US$) [NY.GDP.MKTP.CD]',
       'Angola [AGO] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       ...
       'Zambia [ZMB] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD]',
       'Zambia [ZMB] - GDP (current US$) [NY.GDP.MKTP.CD]',
       'Zambia [ZMB] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       'Zambia [ZMB] - Gross capital formation (current US$) [NE.GDI.TOTL.CD]',
       'Zambia [ZMB] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD]',
       'Zimbabwe [ZWE] - Net official development assistance and official aid received (current US$) [DT.ODA.ALLD.CD]',
       'Zimbabwe [ZWE] - GDP (current US$) [NY.GDP.MKTP.CD]',
       'Zimbabwe [ZWE] - GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       'Zimbabwe [ZWE] - Gross capital formation (current US$) [NE.GDI.TOTL.CD]',
       'Zimbabwe [ZWE] - Gross domestic savings (current US$) [NY.GDS.TOTL.CD]'],
      dtype='object', length=272)

In [68]:
# df['Country'] = df.columns.str.extract(r'\[(.*?)\]')
# df['Year'] = df.columns.str.extract(r'\[([A-Z]{3})\]')

In [69]:
countries = df.columns.str.split(' \[', expand=True).get_level_values(0).unique()

# Initializing an empty DataFrame to store the reformatted data
new_df = pd.DataFrame(columns=['Country', 'Year', 'Net official development assistance and official aid received (current US$)', 
                               'GDP (current US$)', 'GDP growth (annual %)', 'Gross capital formation (current US$)', 
                               'Gross domestic savings (current US$)'])

In [70]:
new_df

Empty DataFrame
Columns: [Country, Year, Net official development assistance and official aid received (current US$), GDP (current US$), GDP growth (annual %), Gross capital formation (current US$), Gross domestic savings (current US$)]
Index: []

In [71]:
country_codes = df.columns.str.extract(r'\[([A-Z]+)\]', expand=False).unique()

country_data_dict = {}

for code in country_codes:
    country_columns = [col for col in df.columns if f'[{code}]' in col]
    
    country_data = df[['Time'] + country_columns]
    
    country_data.columns = ['Time'] + [col.split('[')[0].strip() for col in country_columns]
    
    country_data_dict[code] = country_data

In [72]:
country_data_dict['DZA']

,Time,Algeria,Algeria,Algeria,Algeria,Algeria
0,1980,205160003.662109,4.234583e+10,0.790607,1.654745e+10,1.824128e+10
1,1981,167070007.324219,4.434859e+10,2.999996,1.640481e+10,1.804992e+10
2,1982,134699996.948242,4.520717e+10,6.400004,1.685470e+10,1.772574e+10
3,1983,93279998.779297,4.880137e+10,5.400003,1.833445e+10,1.937855e+10
4,1984,120980003.356934,5.369855e+10,5.599997,1.888279e+10,1.793965e+10
5,1985,172149993.896484,5.793787e+10,3.699997,2.002864e+10,1.819882e+10
6,1986,167330001.831055,6.369201e+10,0.400001,2.137244e+10,1.480122e+10
7,1987,213449996.948242,6.674582e+10,-0.699998,1.839273e+10,1.562970e+10
8,1988,171979995.727539,5.908940e+10,-1.000005,1.633200e+10,1.213911e+10
9,1989,158210006.713867,5.563472e+10,4.400002,1.673116e+10,1.123735e+10
10,1990,331649993.896484,6.204851e+10,0.800001,1.773931e+10,1.681271e+10
11,1991,211169998.168945,4.571568e+10,-1.200001,1.455648e+10,1.707909e+10
12,1992,374790008.544922,4.800313e+10,1.800002,1.476456e+10,1.546065e+10
13,1993,326309997.558594,4.994558e+10,-2.100001,1.452962e+10,1.385283e+10
14,1994,295489990.234375,4.254318e+10,-0.899997,1.279705e+10,1.129826e+10
15,1995,295739990.234375,4.176429e+10,3.799995,1.290874e+10,1.173873e+10
16,1996,306880004.882813,4.694155e+10,4.099998,1.205385e+10,1.478385e+10
17,1997,247889999.389648,4.817761e+10,1.100000,1.081442e+10,1.542439e+10
18,1998,419869995.117188,4.818778e+10,5.100004,1.308225e+10,1.311225e+10
19,1999,137979995.727539,4.864067e+10,3.200002,1.276705e+10,1.537960e+10
20,2000,199960006.713867,5.479040e+10,3.800000,1.291076e+10,2.457076e+10
21,2001,198860000.610352,5.474470e+10,3.000000,1.469406e+10,2.272644e+10
22,2002,186119995.117188,5.676036e+10,5.600000,1.739896e+10,2.300399e+10
23,2003,239240005.493164,6.786385e+10,7.200000,2.059034e+10,3.034433e+10
24,2004,316970001.220703,8.533258e+10,4.300000,2.838464e+10,4.067682e+10
25,2005,347380004.882813,1.031982e+11,5.900000,3.266885e+10,5.654044e+10
26,2006,240679992.675781,1.170273e+11,1.700000,3.530767e+10,6.677790e+10
27,2007,395010009.765625,1.349771e+11,3.400000,4.652590e+10,7.648838e+10
28,2008,324829986.572266,1.710007e+11,2.400000,6.386609e+10,9.680453e+10
29,2009,302390014.648438,1.372110e+11,1.600000,6.431966e+10,6.352243e+10
30,2010,201250000,1.612073e+11,3.600000,6.678866e+10,7.810934e+10
31,2011,193350006.103516,2.000131e+11,2.900000,7.611139e+10,9.631659e+10
32,2012,147320007.324219,2.090591e+11,3.400000,8.185234e+10,9.937497e+10
33,2013,203419998.168945,2.097550e+11,2.800000,9.105708e+10,9.692054e+10
34,2014,160619995.117188,2.138100e+11,3.800000,9.755417e+10,9.430436e+10
35,2015,71129997.253418,1.659792e+11,3.700000,8.428539e+10,6.212466e+10
36,2016,144550003.051758,1.600342e+11,3.200000,8.126173e+10,5.856777e+10
37,2017,174679992.675781,1.700970e+11,1.300000,8.257144e+10,6.546494e+10
38,2018,144610000.610352,1.749107e+11,1.200000,8.233200e+10,7.123707e+10
39,2019,172000000,1.717603e+11,1.000000,7.675934e+10,6.579946e+10
40,2020,209619995.117188,1.457435e+11,-5.100000,6.386342e+10,4.871869e+10
41,2021,214380004.882813,1.634724e+11,3.400000,6.200153e+10,6.244873e+10
42,2022,..,1.949984e+11,3.200002,6.498258e+10,8.765662e+10
43,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN
46,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN
47,Last Updated: 12/18/2023,NaN,NaN,NaN,NaN,NaN

In [74]:
for country, data in country_data_dict.items():
    print(data)
    country_name = data.columns[1].split('[')[0].strip()
    print(country_name)
    
    data['Country'] = country_name

                                                Time
0                                               1980
1                                               1981
2                                               1982
3                                               1983
4                                               1984
5                                               1985
6                                               1986
7                                               1987
8                                               1988
9                                               1989
10                                              1990
11                                              1991
12                                              1992
13                                              1993
14                                              1994
15                                              1995
16                                              1996
17                                              1997
18                                              1998
19                                              1999
20                                              2000
21                                              2001
22                                              2002
23                                              2003
24                                              2004
25                                              2005
26                                              2006
27                                              2007
28                                              2008
29                                              2009
30                                              2010
31                                              2011
32                                              2012
33                                              2013
34                                              2014
35                                              2015
36                                              2016
37                                              2017
38                                              2018
39                                              2019
40                                              2020
41                                              2021
42                                              2022
43                                               NaN
44                                               NaN
45                                               NaN
46  Data from database: World Development Indicators
47                          Last Updated: 12/18/2023

IndexError: index 1 is out of bounds for axis 0 with size 1

In [61]:
country_data_dict['DZA']

,Time,Algeria,Algeria,Algeria,Algeria,Algeria
0,1980,205160003.662109,4.234583e+10,0.790607,1.654745e+10,1.824128e+10
1,1981,167070007.324219,4.434859e+10,2.999996,1.640481e+10,1.804992e+10
2,1982,134699996.948242,4.520717e+10,6.400004,1.685470e+10,1.772574e+10
3,1983,93279998.779297,4.880137e+10,5.400003,1.833445e+10,1.937855e+10
4,1984,120980003.356934,5.369855e+10,5.599997,1.888279e+10,1.793965e+10
5,1985,172149993.896484,5.793787e+10,3.699997,2.002864e+10,1.819882e+10
6,1986,167330001.831055,6.369201e+10,0.400001,2.137244e+10,1.480122e+10
7,1987,213449996.948242,6.674582e+10,-0.699998,1.839273e+10,1.562970e+10
8,1988,171979995.727539,5.908940e+10,-1.000005,1.633200e+10,1.213911e+10
9,1989,158210006.713867,5.563472e+10,4.400002,1.673116e+10,1.123735e+10
10,1990,331649993.896484,6.204851e+10,0.800001,1.773931e+10,1.681271e+10
11,1991,211169998.168945,4.571568e+10,-1.200001,1.455648e+10,1.707909e+10
12,1992,374790008.544922,4.800313e+10,1.800002,1.476456e+10,1.546065e+10
13,1993,326309997.558594,4.994558e+10,-2.100001,1.452962e+10,1.385283e+10
14,1994,295489990.234375,4.254318e+10,-0.899997,1.279705e+10,1.129826e+10
15,1995,295739990.234375,4.176429e+10,3.799995,1.290874e+10,1.173873e+10
16,1996,306880004.882813,4.694155e+10,4.099998,1.205385e+10,1.478385e+10
17,1997,247889999.389648,4.817761e+10,1.100000,1.081442e+10,1.542439e+10
18,1998,419869995.117188,4.818778e+10,5.100004,1.308225e+10,1.311225e+10
19,1999,137979995.727539,4.864067e+10,3.200002,1.276705e+10,1.537960e+10
20,2000,199960006.713867,5.479040e+10,3.800000,1.291076e+10,2.457076e+10
21,2001,198860000.610352,5.474470e+10,3.000000,1.469406e+10,2.272644e+10
22,2002,186119995.117188,5.676036e+10,5.600000,1.739896e+10,2.300399e+10
23,2003,239240005.493164,6.786385e+10,7.200000,2.059034e+10,3.034433e+10
24,2004,316970001.220703,8.533258e+10,4.300000,2.838464e+10,4.067682e+10
25,2005,347380004.882813,1.031982e+11,5.900000,3.266885e+10,5.654044e+10
26,2006,240679992.675781,1.170273e+11,1.700000,3.530767e+10,6.677790e+10
27,2007,395010009.765625,1.349771e+11,3.400000,4.652590e+10,7.648838e+10
28,2008,324829986.572266,1.710007e+11,2.400000,6.386609e+10,9.680453e+10
29,2009,302390014.648438,1.372110e+11,1.600000,6.431966e+10,6.352243e+10
30,2010,201250000,1.612073e+11,3.600000,6.678866e+10,7.810934e+10
31,2011,193350006.103516,2.000131e+11,2.900000,7.611139e+10,9.631659e+10
32,2012,147320007.324219,2.090591e+11,3.400000,8.185234e+10,9.937497e+10
33,2013,203419998.168945,2.097550e+11,2.800000,9.105708e+10,9.692054e+10
34,2014,160619995.117188,2.138100e+11,3.800000,9.755417e+10,9.430436e+10
35,2015,71129997.253418,1.659792e+11,3.700000,8.428539e+10,6.212466e+10
36,2016,144550003.051758,1.600342e+11,3.200000,8.126173e+10,5.856777e+10
37,2017,174679992.675781,1.700970e+11,1.300000,8.257144e+10,6.546494e+10
38,2018,144610000.610352,1.749107e+11,1.200000,8.233200e+10,7.123707e+10
39,2019,172000000,1.717603e+11,1.000000,7.675934e+10,6.579946e+10
40,2020,209619995.117188,1.457435e+11,-5.100000,6.386342e+10,4.871869e+10
41,2021,214380004.882813,1.634724e+11,3.400000,6.200153e+10,6.244873e+10
42,2022,..,1.949984e+11,3.200002,6.498258e+10,8.765662e+10
43,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN
46,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN
47,Last Updated: 12/18/2023,NaN,NaN,NaN,NaN,NaN